name: uafinfra
channels:
  - conda-forge
  - defaults
dependencies:
  - fastkml
  - ipython
  - obspy
  - pip
  - pip:
    - git+https://github.com/uafgeotools/waveform_collection.git
    - git+https://github.com/uafgeotools/lts_array.git
    - -e .
